# Generated by Django 5.0.2 on 2024-02-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en stock', 'en stock'), ('en cour de livraison', 'en cour de livraison'), ('livré', 'livré'), ('retourné', 'retourné')], max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.commande')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
