# Generated by Django 5.0.2 on 2024-02-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_laivraison'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laivraison',
            new_name='Livraison',
        ),
    ]
