# Generated by Django 3.2 on 2024-02-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_laivraison_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('adresse', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
