# Generated by Django 4.2.10 on 2024-02-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livraison',
            field=models.CharField(choices=[('en_stock', 'En Stock'), ('en_route', 'En Route'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_stock', max_length=20),
        ),
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
